export const GRID_ALIGNMENT_CONFIG = {
  enableLocalCompaction: true,
  localCompactionBeatModel: 'madmom',
  silentChordValues: ['', 'N', 'N/C', 'N.C.', 'NC'],
  shortIntroAlignment: {
    maxChordChangePenalty: 2,
    minCompetitiveRatio: 0.65,
  },
  longIntroAlignment: {
    maxChordChangePenalty: 16,
    minCompetitiveRatio: 0.75,
    earlyStartWindow: 12,
    minEarlyDownbeatAdvantage: 2,
  },
  // Legacy visual-compaction settings. These are used by gridCompaction.ts,
  // which is retained for old-vs-new comparison tests, not production assembly.
  beat4BiasCorrection: {
    enabled: true,
    minStarts: 12,
    maxDownbeatShare: 0.25,
    minBeat4Share: 0.5,
    minCompetitiveRatio: 0.6,
  },
  leadingBeat2BiasCorrection: {
    enabled: true,
    minStarts: 12,
    maxDownbeatShare: 0.25,
    minBeat2Share: 0.5,
    minCompetitiveRatio: 0.6,
  },
  padding: {
    meaningfulPreBeatSeconds: 0.05,
    minGapRatioForSinglePadding: 0.2,
    fallbackBeatDurationSeconds: 0.5,
  },
  silentRun: {
    minLengthFloor: 2,
    maxExpansionBeats: 0,
  },
  gap: {
    thresholdBeatsMultiplier: 2.5,
    minGapSeconds: 1.1,
    onsetLeadInBeatsMultiplier: 0.35,
    releaseTailBeatsMultiplier: 0.1,
    maxReleaseTailSeconds: 0.08,
  },
  tempo: {
    minConfirmationBeats: 3,
    steadyToleranceRatio: 0.18,
    changeThresholdRatio: 1.15,
    maxShrinkBeats: 3,
    maxTransitionBeats: 4,
  },
  segmentAlignmentSolver: {
    editPenalty: 5,
    leadingExpansionPenalty: 3,
    downbeatReward: 16,
    nearDownbeatPenalty: 7,
    weakBeatPenalty: 3,
    firstStartBonus: 10,
    longRunStartBonus: 5,
    maxLeadingExpansionBeats: 3,
    phrasePhase: {
      minBoundaryBeats: 16,
      lookbehindBeats: 48,
      lookaheadBeats: 64,
      minStarts: 8,
      minPreviousStarts: 4,
      maxCurrentDownbeatShare: 0.35,
      minCorrectedDownbeatShare: 0.38,
      postTempoMinCorrectedDownbeatShare: 0.35,
      minPreviousDownbeatShare: 0.4,
      minDownbeatGain: 4,
      maxAdjustmentBeats: 1,
      minAnchorDownbeatShare: 0.55,
      maxAnchorShrinkBeats: 3,
      maxAnchorWindows: 8,
      minWindowSpacingBeats: 8,
      postTempoLookbehindBeats: 8,
      postTempoLookaheadBeats: 64,
      maxWindows: 8,
    },
  },
  // Legacy leading-expansion scoring used only by gridCompaction.ts.
  leadingExpansion: {
    maxExtraBeats: 3,
    scoreImprovementThreshold: 0.5,
    maxChordStartsToScore: 8,
    primaryStartWeight: 20,
    descendingWeightStart: 12,
    minWeight: 4,
    extraBeatPenalty: 0.25,
  },
  longIntroCompaction: {
    minNaturalSilenceMeasuresForSuppression: 2,
    protectEarlyMusicMeasures: 2,
  },
  localMeterDetection: {
    enabled: true,
    candidateMeters: [3, 4, 5, 7],
    minBeats: 24,
    minSegmentBeats: 18,
    minRunMeasuresBeforeSwitch: 4,
    switchPenalty: 34,
    earlySwitchPenalty: 18,
    minSingleMeterImprovement: 24,
    minMixedMeterImprovement: 24,
    minMixedOddMeterImprovement: 80,
    downbeatReward: 14,
    secondaryStrongBeatReward: 2,
    offDownbeatPenalty: 5,
    longRunStartBonus: 4,
  },
} as const;
