import { MetadataRoute } from 'next';

/**
 * Generate dynamic robots.txt for ChordMini
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://chordmini.com';
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/about',
          '/docs',
          '/help',
          '/analyze',
          '/analyze/*',
          '/lyrics/*',
          '/changelog',
          '/privacy',
          '/terms',
          '/status',
        ],
        disallow: [
          '/api/*',
          '/cache-management',
          '/cache-management/*',
          '/test',
          '/test/*',
          '/test-*',
          '/settings',
          '/settings/*',
          '/_next/*',
          '/temp/*',
          '/cache/*',
          '/scripts/*',
          '/python_backend/*',
          '/node_modules/*',
          '/*.log',
          '/*.tmp',
          '/admin/*',
          '/debug/*',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/about',
          '/docs',
          '/help',
          '/analyze',
          '/analyze/*',
          '/lyrics/*',
          '/changelog',
          '/privacy',
          '/terms',
          '/status',
        ],
        disallow: [
          '/api/*',
          '/cache-management',
          '/cache-management/*',
          '/test',
          '/test/*',
          '/test-*',
          '/settings',
          '/settings/*',
          '/_next/*',
          '/temp/*',
          '/cache/*',
          '/scripts/*',
          '/python_backend/*',
          '/node_modules/*',
          '/*.log',
          '/*.tmp',
          '/admin/*',
          '/debug/*',
        ],
        crawlDelay: 0.5,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/about',
          '/docs',
          '/help',
          '/analyze',
          '/analyze/*',
          '/lyrics/*',
          '/changelog',
          '/privacy',
          '/terms',
          '/status',
        ],
        disallow: [
          '/api/*',
          '/cache-management',
          '/cache-management/*',
          '/test',
          '/test/*',
          '/test-*',
          '/settings',
          '/settings/*',
          '/_next/*',
          '/temp/*',
          '/cache/*',
          '/scripts/*',
          '/python_backend/*',
          '/node_modules/*',
          '/*.log',
          '/*.tmp',
          '/admin/*',
          '/debug/*',
        ],
        crawlDelay: 1,
      },
      {
        // Block AI training bots from accessing user-generated content
        userAgent: [
          'GPTBot',
          'ChatGPT-User',
          'CCBot',
          'anthropic-ai',
          'Claude-Web',
          'PerplexityBot',
          'YouBot',
          'Applebot-Extended',
          'FacebookBot',
          'Meta-ExternalAgent',
          'Meta-ExternalFetcher',
          'OAI-SearchBot',
        ],
        disallow: [
          '/analyze/*',
          '/lyrics/*',
          '/api/*',
          '/cache-management/*',
        ],
        allow: [
          '/',
          '/about',
          '/docs',
          '/help',
          '/privacy',
          '/terms',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
