# Google Cloud Build configuration for ChordMini Backend
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/191567167632-compute@developer.gserviceaccount.com'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chordmini-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chordmini-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'chordmini-backend-full'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chordmini-backend'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '16Gi'
      - '--cpu'
      - '8'
      - '--timeout'
      - '600'
      - '--max-instances'
      - '5'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

# Build timeout (30 minutes for ML model installation)
timeout: 1800s

# Logging configuration for service account
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
